/**
 * @file canbus_msg.h
 * @brief Autogenerated CAN definitions - Generated on 2026-02-09 15:18:23
 * @note DO NOT EDIT MANUALLY
 */
#ifndef CANBUS_MSG_H_
#define CANBUS_MSG_H_

#include <stdint.h>

/* ========================================================================== */
/* --- 16-BIT FEATURE MASKS ---                                               */
/* ========================================================================== */
#define FEATURE_BOX_SW_6GANG_HIGH                                         ((uint16_t)0x8EC0) /**< feature mask for 6-gang switch box, 4 high, 2 low */
#define FEATURE_BOX_SW_3GANG                                              ((uint16_t)0x8E60) /**< feature mask for 3-gang output, 2 high, 1 low */
#define FEATURE_BOX_SW_2GANG_LOW                                          ((uint16_t)0x8E40) /**< feature mask for 2-gang switch box, 2 low */
#define FEATURE_BOX_SW_4GANG                                              ((uint16_t)0x8E80) /**< feature mask for 4-gang switch box, 2 high, 2 low */
#define FEATURE_BOX_SW_4RELAY                                             ((uint16_t)0x8C08) /**< feature mask for 4-gang relay output box */
#define FEATURE_BOX_SW_6GANG_LOW                                          ((uint16_t)0x8EC0) /**< feature mask for 6-gang switch box, 2 high, 4 low */
#define FEATURE_BOX_SW_2GANG_HIGH                                         ((uint16_t)0x8E40) /**< feature mask for 2-gang switch box, 2 high */
#define FEATURE_BOX_SW_8RELAY                                             ((uint16_t)0x8C10) /**< feature mask for 8-gang relay output box */
#define FEATURE_BOX_MULTI_4X4IO                                           ((uint16_t)0xCC08) /**< feature mask for input - output box, 4 in, 4 out */
#define FEATURE_BOX_MULTI_4XTEMP                                          ((uint16_t)0xCC00) /**< feature mask for 4-digital multi temp input box */
#define FEATURE_BOX_MULTI_TVA                                             ((uint16_t)0xBC00) /**< feature mask for temp, volt, current input box */
#define FEATURE_IFACE_8X4_ARGB                                            ((uint16_t)0xC1A4) /**< feature mask for 8x4 argb keypad */
#define FEATURE_IFACE_4X4_ARGB                                            ((uint16_t)0xA1A4) /**< feature mask for 4x4 argb keypad */
#define FEATURE_IFACE_TOUCHSCREEN_TYPE_A                                  ((uint16_t)0x81D8) /**< feature mask for touchscreen type a */
#define FEATURE_IFACE_TOUCHSCREEN_TYPE_B                                  ((uint16_t)0x81D8) /**< feature mask for touchscreen type b */
#define FEATURE_IFACE_NEXTION_TYPE_A                                      ((uint16_t)0x81D8) /**< feature mask for nextion type a */
#define FEATURE_IFACE_NEXTION_TYPE_B                                      ((uint16_t)0x81D8) /**< feature mask for nextion type b */
#define FEATURE_IFACE_6_AXIS_IMU                                          ((uint16_t)0x9180) /**< feature mask for 6-axis IMU */
#define FEATURE_IFACE_3X5_BUTTON_BOX                                      ((uint16_t)0x9F80) /**< feature mask for 3x5 button box */
#define FEATURE_IFACE_4x6_BUTTON_BOX                                      ((uint16_t)0xB180) /**< feature mask for 4x6 button box */
#define FEATURE_DISP_ANALOG_LED_STRIP                                     ((uint16_t)0x81E2) /**< feature mask for analog led strip */
#define FEATURE_DISP_ARGBW_LED_STRIP                                      ((uint16_t)0x81E4) /**< feature mask for argbw led strip */
#define FEATURE_DISP_ARGB_LED_STRIP                                       ((uint16_t)0x8064) /**< feature mask for argb led strip */
#define FEATURE_DISP_OLED                                                 ((uint16_t)0x8040) /**< feature mask for non-touch oled display */
#define FEATURE_DISP_LCD                                                  ((uint16_t)0x8048) /**< feature mask for non-touch lcd display */
#define FEATURE_INPUT_DIGITAL_TEMP                                        ((uint16_t)0x0000) /**< feature mask for input digital temp */
#define FEATURE_INPUT_K_TYPE_TEMP                                         ((uint16_t)0x0008) /**< feature mask for input k type temp */
#define FEATURE_NODE_LASTBOOT                                             ((uint16_t)0x0004) /**< feature mask for last boot timestamp */
#define FEATURE_NODE_PCB_TEMP                                             ((uint16_t)0x0011) /**< feature mask for node pcb temp */
#define FEATURE_NODE_CPU_TEMP                                             ((uint16_t)0x0020) /**< feature mask for node cpu temp */
#define FEATURE_INPUT_EXT_VOLTAGE_SENSOR                                  ((uint16_t)0x0040) /**< feature mask for input ext voltage sensor */
#define FEATURE_NODE_INT_VOLTAGE_SENSOR                                   ((uint16_t)0x0042) /**< feature mask for node int voltage sensor */
#define FEATURE_NODE_INT_CURRENT_SENSOR                                   ((uint16_t)0x0000) /**< feature mask for node int current sensor */
#define FEATURE_INPUT_EXT_CURRENT_SHUNT                                   ((uint16_t)0x0000) /**< feature mask for input ext current shunt */
#define FEATURE_INPUT_EXT_CURRENT_HALL                                    ((uint16_t)0x0010) /**< feature mask for input ext current hall */
#define FEATURE_SENSOR_RESERVED_72A                                       ((uint16_t)0x0044) /**< feature mask for sensor reserved 72a */
#define FEATURE_SENSOR_RESERVED_72B                                       ((uint16_t)0x0000) /**< feature mask for sensor reserved 72b */
#define FEATURE_GPS_ALTITUDE                                              ((uint16_t)0x0000) /**< feature mask for GPS altitude */
#define FEATURE_GPS_STATUS                                                ((uint16_t)0x0000) /**< feature mask for GPS status */
#define FEATURE_SENSOR_RESERVED_72E                                       ((uint16_t)0x0040) /**< feature mask for sensor reserved 72e */
#define FEATURE_SENSOR_RESERVED_72F                                       ((uint16_t)0x0020) /**< feature mask for sensor reserved 72f */
#define FEATURE_IMU_X_AXIS_SENSOR                                         ((uint16_t)0x0000) /**< feature mask for IMU X Axis sensor */
#define FEATURE_IMU_Y_AXIS_SENSOR                                         ((uint16_t)0x0011) /**< feature mask for IMU Y Axis sensor */
#define FEATURE_IMU_Z_AXIS_SENSOR                                         ((uint16_t)0x0010) /**< feature mask for IMU Z Axis sensor */
#define FEATURE_IMU_X_GYRO_SENSOR                                         ((uint16_t)0x0008) /**< feature mask for IMU X Gyro sensor */
#define FEATURE_IMU_Y_GYRO_SENSOR                                         ((uint16_t)0x0044) /**< feature mask for IMU Y Gyro sensor */
#define FEATURE_GPS_UTC_TIME                                              ((uint16_t)0x0001) /**< feature mask for GPS utc time */
#define FEATURE_GPS_LATITUDE                                              ((uint16_t)0x0002) /**< feature mask for GPS latitude */
#define FEATURE_GPS_NS_IND                                                ((uint16_t)0x0002) /**< feature mask for GPS NS IND */
#define FEATURE_OUT_LOW_CURRENT_SW                                        ((uint16_t)0x0400) /**< feature mask for low current solid state switch */
#define FEATURE_OUT_OPEN_DRAIN                                            ((uint16_t)0x0200) /**< feature mask for open drain output */
#define FEATURE_OUT_MECH_RELAY                                            ((uint16_t)0x0200) /**< feature mask for mechanical relay */
#define FEATURE_OUT_RESERVED_744                                          ((uint16_t)0x0200) /**< feature mask for out reserved 744 */
#define FEATURE_OUT_RESERVED_745                                          ((uint16_t)0x0200) /**< feature mask for out reserved 745 */
#define FEATURE_OUT_RESERVED_746                                          ((uint16_t)0x0200) /**< feature mask for out reserved 746 */
#define FEATURE_OUT_RESERVED_747                                          ((uint16_t)0x0200) /**< feature mask for out reserved 747 */
#define FEATURE_OUT_RESERVED_74B                                          ((uint16_t)0x0100) /**< feature mask for out reserved 74b */
#define FEATURE_OUT_RESERVED_74C                                          ((uint16_t)0x0100) /**< feature mask for out reserved 74c */
#define FEATURE_OUT_RESERVED_74D                                          ((uint16_t)0x0100) /**< feature mask for out reserved 74d */
#define FEATURE_OUT_RESERVED_74E                                          ((uint16_t)0x0100) /**< feature mask for out reserved 74e */
#define FEATURE_OUT_RESERVED_74F                                          ((uint16_t)0x0100) /**< feature mask for out reserved 74f */
#define FEATURE_GPS_LONGITUDE                                             ((uint16_t)0x0100) /**< feature mask for GPS longitude */
#define FEATURE_GPS_EW_IND                                                ((uint16_t)0x0100) /**< feature mask for GPS EW IND */

/* ========================================================================== */
/* --- CAN MESSAGE IDS AND DLCS ---                                           */
/* ========================================================================== */
#define CANERR_OVER_CURRENT_ID                                            (0x100) /**< error condition over current */
#define CANERR_OVER_CURRENT_DLC                                           (8)

#define CANERR_OVER_VOLTAGE_ID                                            (0x101) /**< error condition over temp */
#define CANERR_OVER_VOLTAGE_DLC                                           (8)

#define CANNERR_OVER_VOLTAGE_ID                                           (0x102) /**< error condition over volt */
#define CANNERR_OVER_VOLTAGE_DLC                                          (8)

#define CANERR_GEN_ALARM_ID                                               (0x103) /**< general alarm */
#define CANERR_GEN_ALARM_DLC                                              (0)

#define CANERR_STORED_ERROR_ID                                            (0x104) /**< node has a stored error to transmit */
#define CANERR_STORED_ERROR_DLC                                           (0)

#define CANERR_RESERVED_105_ID                                            (0x105) /**< canerr reserved 105 */
#define CANERR_RESERVED_105_DLC                                           (0)

#define CANERR_RESERVED_106_ID                                            (0x106) /**< canerr reserved 106 */
#define CANERR_RESERVED_106_DLC                                           (0)

#define CANERR_RESERVED_107_ID                                            (0x107) /**< canerr reserved 107 */
#define CANERR_RESERVED_107_DLC                                           (0)

#define CANERR_RESERVED_108_ID                                            (0x108) /**< canerr reserved 108 */
#define CANERR_RESERVED_108_DLC                                           (0)

#define CANERR_RESERVED_109_ID                                            (0x109) /**< canerr reserved 109 */
#define CANERR_RESERVED_109_DLC                                           (0)

#define SW_RESERVED_110_ID                                                (0x110) /**< sw reserved 110 */
#define SW_RESERVED_110_DLC                                               (0)

#define SW_RESERVED_111_ID                                                (0x111) /**< sw reserved 111 */
#define SW_RESERVED_111_DLC                                               (0)

#define SW_SET_MODE_ID                                                    (0x112) /**< set switch mode */
#define SW_SET_MODE_DLC                                                   (6)

#define SW_SET_OFF_ID                                                     (0x113) /**< switch off */
#define SW_SET_OFF_DLC                                                    (5)

#define SW_SET_ON_ID                                                      (0x114) /**< switch on */
#define SW_SET_ON_DLC                                                     (5)

#define SW_MOM_PRESS_ID                                                   (0x115) /**< switch momentary press */
#define SW_MOM_PRESS_DLC                                                  (5)

#define SW_SET_MOM_DUR_ID                                                 (0x116) /**< set momentary switch duration ms */
#define SW_SET_MOM_DUR_DLC                                                (7)

#define SW_SET_PWM_DUTY_ID                                                (0x117) /**< switch set pwm duty */
#define SW_SET_PWM_DUTY_DLC                                               (7)

#define SW_SET_PWM_FREQ_ID                                                (0x118) /**< switch set pwm freq */
#define SW_SET_PWM_FREQ_DLC                                               (7)

#define SW_SET_BLINK_DELAY_ID                                             (0x119) /**< switch set blink delay in tenths of a second 1-100 */
#define SW_SET_BLINK_DELAY_DLC                                            (7)

#define SW_SET_STROBE_PAT_ID                                              (0x11A) /**< switch set strobe pattern */
#define SW_SET_STROBE_PAT_DLC                                             (6)

#define SW_SET_STATE_MEM_ID                                               (0x11B) /**< enable / disable switch last state memory */
#define SW_SET_STATE_MEM_DLC                                              (6)

#define SW_RESERVED_11C_ID                                                (0x11C) /**< sw reserved 11c */
#define SW_RESERVED_11C_DLC                                               (0)

#define SW_RESERVED_11D_ID                                                (0x11D) /**< sw reserved 11d */
#define SW_RESERVED_11D_DLC                                               (0)

#define SW_RESERVED_11E_ID                                                (0x11E) /**< sw reserved 11e */
#define SW_RESERVED_11E_DLC                                               (0)

#define SW_RESERVED_11F_ID                                                (0x11F) /**< sw reserved 11f */
#define SW_RESERVED_11F_DLC                                               (0)

#define SW_RESERVED_13A_ID                                                (0x13A) /**< sw reserved 13a */
#define SW_RESERVED_13A_DLC                                               (0)

#define SW_RESERVED_13B_ID                                                (0x13B) /**< sw reserved 13b */
#define SW_RESERVED_13B_DLC                                               (0)

#define SW_RESERVED_13C_ID                                                (0x13C) /**< sw reserved 13c */
#define SW_RESERVED_13C_DLC                                               (0)

#define SW_RESERVED_13D_ID                                                (0x13D) /**< sw reserved 13d */
#define SW_RESERVED_13D_DLC                                               (0)

#define SW_RESERVED_13E_ID                                                (0x13E) /**< sw reserved 13e */
#define SW_RESERVED_13E_DLC                                               (0)

#define SW_RESERVED_13F_ID                                                (0x13F) /**< sw reserved 13f */
#define SW_RESERVED_13F_DLC                                               (0)

#define SET_DISPLAY_OFF_ID                                                (0x200) /**< set display off */
#define SET_DISPLAY_OFF_DLC                                               (5)

#define SET_DISPLAY_ON_ID                                                 (0x201) /**< set display on */
#define SET_DISPLAY_ON_DLC                                                (5)

#define SET_DISPLAY_CLEAR_ID                                              (0x202) /**< set display clear */
#define SET_DISPLAY_CLEAR_DLC                                             (5)

#define SET_DISPLAY_FLASH_ID                                              (0x203) /**< set display flash */
#define SET_DISPLAY_FLASH_DLC                                             (6)

#define SET_DISPLAY_BACKLIGHT_COLOR_ID                                    (0x204) /**< set display backlight color */
#define SET_DISPLAY_BACKLIGHT_COLOR_DLC                                   (7)

#define SET_DISPLAY_BACKLIGHT_BRIGHTNESS_ID                               (0x205) /**< set display backlight brightness */
#define SET_DISPLAY_BACKLIGHT_BRIGHTNESS_DLC                              (7)

#define REQ_DISPLAY_CONFIG_ID                                             (0x206) /**< req display config */
#define REQ_DISPLAY_CONFIG_DLC                                            (7)

#define REQ_DISPLAY_DATA_ID                                               (0x207) /**< req display data */
#define REQ_DISPLAY_DATA_DLC                                              (7)

#define SET_OLED_FIELD_COLOR_ID                                           (0x208) /**< set oled field color */
#define SET_OLED_FIELD_COLOR_DLC                                          (7)

#define SET_OLED_FIELD_BLINK_ID                                           (0x209) /**< set oled field blink */
#define SET_OLED_FIELD_BLINK_DLC                                          (7)

#define SET_OLED_FIELD_STROBE_ID                                          (0x20A) /**< set oled field strobe */
#define SET_OLED_FIELD_STROBE_DLC                                         (6)

#define SET_DISPLAY_RESERVED_20B_ID                                       (0x20B) /**< set display reserved 20b */
#define SET_DISPLAY_RESERVED_20B_DLC                                      (4)

#define SET_DISPLAY_RESERVED_20C_ID                                       (0x20C) /**< set display reserved 20c */
#define SET_DISPLAY_RESERVED_20C_DLC                                      (4)

#define DISPLAY_DATA_MSG_ID                                               (0x20D) /**< display data msg */
#define DISPLAY_DATA_MSG_DLC                                              (8)

#define DISPLAY_DATA_ACK_ID                                               (0x20E) /**< display data ack */
#define DISPLAY_DATA_ACK_DLC                                              (8)

#define SET_DISPLAY_RESERVED_20F_ID                                       (0x20F) /**< set display reserved 20f */
#define SET_DISPLAY_RESERVED_20F_DLC                                      (4)

#define SET_ARGB_STRIP_COLOR_ID                                           (0x210) /**< set argb strip color */
#define SET_ARGB_STRIP_COLOR_DLC                                          (7)

#define SET_ARGBW_STRIP_COLOR_ID                                          (0x211) /**< set argbw strip color */
#define SET_ARGBW_STRIP_COLOR_DLC                                         (7)

#define SET_ANALOG_STRIP_COLOR_ID                                         (0x212) /**< set analog strip color */
#define SET_ANALOG_STRIP_COLOR_DLC                                        (7)

#define SET_ADDR_STRIP_EFFECT_ID                                          (0x213) /**< set addr strip effect */
#define SET_ADDR_STRIP_EFFECT_DLC                                         (7)

#define SET_LED_STRIP_BRIGHTNESS_ID                                       (0x214) /**< set led strip brightness */
#define SET_LED_STRIP_BRIGHTNESS_DLC                                      (7)

#define SET_LED_STRIP_OFF_ID                                              (0x215) /**< set led strip off */
#define SET_LED_STRIP_OFF_DLC                                             (5)

#define SET_LED_STRIP_ON_ID                                               (0x216) /**< set led strip on */
#define SET_LED_STRIP_ON_DLC                                              (5)

#define SET_LED_RESERVED_217_ID                                           (0x217) /**< set led reserved 217 */
#define SET_LED_RESERVED_217_DLC                                          (4)

#define SET_LED_RESERVED_218_ID                                           (0x218) /**< set led reserved 218 */
#define SET_LED_RESERVED_218_DLC                                          (4)

#define SET_LED_RESERVED_219_ID                                           (0x219) /**< set led reserved 219 */
#define SET_LED_RESERVED_219_DLC                                          (4)

#define SET_LED_RESERVED_21A_ID                                           (0x21A) /**< set led reserved 21a */
#define SET_LED_RESERVED_21A_DLC                                          (4)

#define SET_LED_RESERVED_21B_ID                                           (0x21B) /**< set led reserved 21b */
#define SET_LED_RESERVED_21B_DLC                                          (4)

#define SET_LED_RESERVED_21C_ID                                           (0x21C) /**< set led reserved 21c */
#define SET_LED_RESERVED_21C_DLC                                          (4)

#define SET_LED_RESERVED_21D_ID                                           (0x21D) /**< set led reserved 21d */
#define SET_LED_RESERVED_21D_DLC                                          (4)

#define SET_LED_RESERVED_21E_ID                                           (0x21E) /**< set led reserved 21e */
#define SET_LED_RESERVED_21E_DLC                                          (4)

#define SET_LED_RESERVED_21F_ID                                           (0x21F) /**< set led reserved 21f */
#define SET_LED_RESERVED_21F_DLC                                          (4)

#define SET_ARGB_BUTTON_COLOR_ID                                          (0x220) /**< set argb button color */
#define SET_ARGB_BUTTON_COLOR_DLC                                         (7)

#define SET_ARGB_BUTTON_LED_MODE_ID                                       (0x221) /**< set argb button led mode */
#define SET_ARGB_BUTTON_LED_MODE_DLC                                      (6)

#define SET_BUTTON_MODE_ID                                                (0x222) /**< set button mode 0 disabled, 1 toggle, 2 momentary */
#define SET_BUTTON_MODE_DLC                                               (4)

#define SET_BUTTON_RESERVED_223_ID                                        (0x223) /**< set button reserved 223 */
#define SET_BUTTON_RESERVED_223_DLC                                       (4)

#define SET_BUTTON_RESERVED_224_ID                                        (0x224) /**< set button reserved 224 */
#define SET_BUTTON_RESERVED_224_DLC                                       (4)

#define SET_BUTTON_RESERVED_225_ID                                        (0x225) /**< set button reserved 225 */
#define SET_BUTTON_RESERVED_225_DLC                                       (4)

#define SET_BUTTON_RESERVED_226_ID                                        (0x226) /**< set button reserved 226 */
#define SET_BUTTON_RESERVED_226_DLC                                       (4)

#define SET_BUTTON_RESERVED_227_ID                                        (0x227) /**< set button reserved 227 */
#define SET_BUTTON_RESERVED_227_DLC                                       (4)

#define SET_BUTTON_RESERVED_228_ID                                        (0x228) /**< set button reserved 228 */
#define SET_BUTTON_RESERVED_228_DLC                                       (4)

#define SET_BUTTON_RESERVED_229_ID                                        (0x229) /**< set button reserved 229 */
#define SET_BUTTON_RESERVED_229_DLC                                       (4)

#define SET_BUTTON_RESERVED_22A_ID                                        (0x22A) /**< set button reserved 22a */
#define SET_BUTTON_RESERVED_22A_DLC                                       (4)

#define SET_BUTTON_RESERVED_22B_ID                                        (0x22B) /**< set button reserved 22b */
#define SET_BUTTON_RESERVED_22B_DLC                                       (4)

#define SET_BUTTON_RESERVED_22C_ID                                        (0x22C) /**< set button reserved 22c */
#define SET_BUTTON_RESERVED_22C_DLC                                       (4)

#define SET_BUTTON_RESERVED_22D_ID                                        (0x22D) /**< set button reserved 22d */
#define SET_BUTTON_RESERVED_22D_DLC                                       (4)

#define SET_BUTTON_RESERVED_22E_ID                                        (0x22E) /**< set button reserved 22e */
#define SET_BUTTON_RESERVED_22E_DLC                                       (4)

#define SET_BUTTON_RESERVED_22F_ID                                        (0x22F) /**< set button reserved 22f */
#define SET_BUTTON_RESERVED_22F_DLC                                       (4)

#define ACK_INTRO_ID                                                      (0x400) /**< acknowledge introduction, clear flag on remote device */
#define ACK_INTRO_DLC                                                     (4)

#define REQ_NODE_INTRO_ID                                                 (0x401) /**< general intro request for all node types */
#define REQ_NODE_INTRO_DLC                                                (4)

#define MSG_NORM_OPER_ID                                                  (0x402) /**< message to all nodes to being normal operation, sent after introduction and enumeration are complete */
#define MSG_NORM_OPER_DLC                                                 (4)

#define MSG_HALT_OPER_ID                                                  (0x403) /**< message to all nodes to stop transmitting messages and wait for instructions */
#define MSG_HALT_OPER_DLC                                                 (4)

#define REQ_NODECHECK_ID                                                  (0x404) /**< remote nodes should respond with their node id and last boot timestamp */
#define REQ_NODECHECK_DLC                                                 (4)

#define REQ_HEALTHCHECK_ID                                                (0x405) /**< remote nodes should respond with diagnostic sensor data */
#define REQ_HEALTHCHECK_DLC                                               (4)

#define REQ_IFACE_ID                                                      (0x406) /**< req interfaces node include buttons, displays leds and sensors */
#define REQ_IFACE_DLC                                                     (4)

#define REQ_SWITCHBOX_ID                                                  (0x407) /**< req switch boxes nodes include anything that controls a load */
#define REQ_SWITCHBOX_DLC                                                 (4)

#define REQ_RESERVED_408_ID                                               (0x408) /**< req reserved 408 */
#define REQ_RESERVED_408_DLC                                              (4)

#define REQ_RESERVED_409_ID                                               (0x409) /**< req reserved 409 */
#define REQ_RESERVED_409_DLC                                              (4)

#define REQ_RESERVED_40A_ID                                               (0x40A) /**< req reserved 40a */
#define REQ_RESERVED_40A_DLC                                              (4)

#define REQ_RESERVED_40B_ID                                               (0x40B) /**< req reserved 40b */
#define REQ_RESERVED_40B_DLC                                              (4)

#define DATA_EPOCH_ID                                                     (0x40C) /**< epoch timestamp from controller */
#define DATA_EPOCH_DLC                                                    (8)

#define DATA_SENSOR_MSG_ID                                                (0x40D) /**< controller assigned message id to use for transferring sensor data range 52A:53F */
#define DATA_SENSOR_MSG_DLC                                               (6)

#define REQ_RESERVED_40E_ID                                               (0x40E) /**< req reserved 40e */
#define REQ_RESERVED_40E_DLC                                              (4)

#define REQ_RESERVED_40F_ID                                               (0x40F) /**< req reserved 40f */
#define REQ_RESERVED_40F_DLC                                              (4)

#define REQ_BUTTONS_ID                                                    (0x410) /**< req buttons */
#define REQ_BUTTONS_DLC                                                   (4)

#define REQ_OUTPUTS_ID                                                    (0x411) /**< req outputs */
#define REQ_OUTPUTS_DLC                                                   (4)

#define REQ_DISPLAYS_ID                                                   (0x412) /**< req displays */
#define REQ_DISPLAYS_DLC                                                  (4)

#define REQ_TEMP_SENSOR_ID                                                (0x413) /**< req temp sensor */
#define REQ_TEMP_SENSOR_DLC                                               (4)

#define REQ_VOLT_SENSOR_ID                                                (0x414) /**< req volt sensor */
#define REQ_VOLT_SENSOR_DLC                                               (4)

#define REQ_AMP_SENSOR_ID                                                 (0x415) /**< req amp sensor */
#define REQ_AMP_SENSOR_DLC                                                (4)

#define REQ_CLOSURE_INPUT_ID                                              (0x416) /**< req closure input */
#define REQ_CLOSURE_INPUT_DLC                                             (4)

#define REQ_AMBIENT_LIGHT_ID                                              (0x417) /**< req ambient light sensors */
#define REQ_AMBIENT_LIGHT_DLC                                             (4)

#define REQ_IMU_SENSORS_ID                                                (0x418) /**< req imu sensors */
#define REQ_IMU_SENSORS_DLC                                               (4)

#define REQ_RESERVED_419_ID                                               (0x419) /**< req reserved 419 */
#define REQ_RESERVED_419_DLC                                              (4)

#define REQ_RESERVED_41A_ID                                               (0x41A) /**< req reserved 41a */
#define REQ_RESERVED_41A_DLC                                              (4)

#define REQ_RESERVED_41B_ID                                               (0x41B) /**< req reserved 41b */
#define REQ_RESERVED_41B_DLC                                              (4)

#define REQ_RESERVED_41C_ID                                               (0x41C) /**< req reserved 41c */
#define REQ_RESERVED_41C_DLC                                              (4)

#define REQ_RESERVED_41D_ID                                               (0x41D) /**< req reserved 41d */
#define REQ_RESERVED_41D_DLC                                              (4)

#define REQ_RESERVED_41E_ID                                               (0x41E) /**< req reserved 41e */
#define REQ_RESERVED_41E_DLC                                              (4)

#define REQ_RESERVED_41F_ID                                               (0x41F) /**< req reserved 41f */
#define REQ_RESERVED_41F_DLC                                              (4)

#define REQ_RESERVED_420_ID                                               (0x420) /**< req reserved 420 */
#define REQ_RESERVED_420_DLC                                              (4)

#define REQ_RESERVED_421_ID                                               (0x421) /**< req reserved 421 */
#define REQ_RESERVED_421_DLC                                              (4)

#define REQ_RESERVED_43B_ID                                               (0x43B) /**< req reserved 43b */
#define REQ_RESERVED_43B_DLC                                              (4)

#define REQ_RESERVED_43C_ID                                               (0x43C) /**< req reserved 43c */
#define REQ_RESERVED_43C_DLC                                              (4)

#define REQ_RESERVED_43D_ID                                               (0x43D) /**< req reserved 43d */
#define REQ_RESERVED_43D_DLC                                              (4)

#define REQ_RESERVED_43E_ID                                               (0x43E) /**< req reserved 43e */
#define REQ_RESERVED_43E_DLC                                              (4)

#define REQ_RESERVED_43F_ID                                               (0x43F) /**< req reserved 43f */
#define REQ_RESERVED_43F_DLC                                              (4)

#define DATA_BUTTON_DOWN_ID                                               (0x500) /**< button down */
#define DATA_BUTTON_DOWN_DLC                                              (7)

#define DATA_BUTTON_UP_ID                                                 (0x501) /**< button up */
#define DATA_BUTTON_UP_DLC                                                (7)

#define DATA_KEYSWITCH_LOCK_ID                                            (0x502) /**< keyswitch lock */
#define DATA_KEYSWITCH_LOCK_DLC                                           (7)

#define DATA_KEYSWITCH_UNLOCK_ID                                          (0x503) /**< keyswitch unlock */
#define DATA_KEYSWITCH_UNLOCK_DLC                                         (7)

#define DATA_DIAL_CLOCKWISE_ID                                            (0x504) /**< dial clockwise */
#define DATA_DIAL_CLOCKWISE_DLC                                           (7)

#define DATA_DIAL_COUNTER_CLOCKWISE_ID                                    (0x505) /**< dial counter clockwise */
#define DATA_DIAL_COUNTER_CLOCKWISE_DLC                                   (7)

#define DATA_DIAL_CLICK_ID                                                (0x506) /**< dial click */
#define DATA_DIAL_CLICK_DLC                                               (7)

#define DATA_EXTERNAL_CURRENT1_ID                                         (0x507) /**< external current1 */
#define DATA_EXTERNAL_CURRENT1_DLC                                        (8)

#define DATA_CONTACT_CLOSED_ID                                            (0x508) /**< contact closed */
#define DATA_CONTACT_CLOSED_DLC                                           (7)

#define DATA_CONTACT_OPENED_ID                                            (0x509) /**< contact opened */
#define DATA_CONTACT_OPENED_DLC                                           (7)

#define DATA_INTERNAL_PCB_TEMP_ID                                         (0x50A) /**< internal pcb temp */
#define DATA_INTERNAL_PCB_TEMP_DLC                                        (8)

#define DATA_INTERNAL_PCB_VOLTS_ID                                        (0x50B) /**< internal pcb volts */
#define DATA_INTERNAL_PCB_VOLTS_DLC                                       (8)

#define DATA_INTERNAL_PCB_CURRENT_ID                                      (0x50C) /**< internal pcb current */
#define DATA_INTERNAL_PCB_CURRENT_DLC                                     (8)

#define DATA_EXTERNAL_TEMPERATURE1_ID                                     (0x50D) /**< external temperature1 */
#define DATA_EXTERNAL_TEMPERATURE1_DLC                                    (8)

#define DATA_EXTERNAL_VOLTS1_ID                                           (0x50E) /**< external volts1 */
#define DATA_EXTERNAL_VOLTS1_DLC                                          (8)

#define DATA_EXTERNAL_CURRENT2_ID                                         (0x50F) /**< external current2 */
#define DATA_EXTERNAL_CURRENT2_DLC                                        (8)

#define DATA_AMBIENT_LIGHT_USE_PRIV_MSG_ID                                (0x510) /**< ambient light USE PRIV MSG */
#define DATA_AMBIENT_LIGHT_USE_PRIV_MSG_DLC                               (5)

#define DATA_IMU_X_AXIS_ID                                                (0x511) /**< IMU X Axis USE PRIV MSG */
#define DATA_IMU_X_AXIS_DLC                                               (5)

#define DATA_IMU_Y_AXIS_ID                                                (0x512) /**< IMU Y Axis USE PRIV MSG */
#define DATA_IMU_Y_AXIS_DLC                                               (5)

#define DATA_IMU_Z_AXIS_ID                                                (0x513) /**< IMU Z Axis USE PRIV MSG */
#define DATA_IMU_Z_AXIS_DLC                                               (5)

#define DATA_IMU_X_GYRO_ID                                                (0x514) /**< IMU X Gyro USE PRIV MSG */
#define DATA_IMU_X_GYRO_DLC                                               (5)

#define DATA_IMU_Y_GYRO_ID                                                (0x515) /**< IMU Y Gyro USE PRIV MSG */
#define DATA_IMU_Y_GYRO_DLC                                               (5)

#define DATA_IMU_Z_GYRO_ID                                                (0x516) /**< IMU Z Gyro USE PRIV MSG */
#define DATA_IMU_Z_GYRO_DLC                                               (5)

#define DATA_IMU_TEMPERATURE_ID                                           (0x517) /**< IMU temperature */
#define DATA_IMU_TEMPERATURE_DLC                                          (8)

#define DATA_ANALOG_KNOB1_ID                                              (0x518) /**< analog knob1 */
#define DATA_ANALOG_KNOB1_DLC                                             (6)

#define DATA_ANALOG_KNOB2_ID                                              (0x519) /**< analog knob2 */
#define DATA_ANALOG_KNOB2_DLC                                             (6)

#define DATA_NODE_CPU_TEMP_ID                                             (0x51A) /**< node cpu temp */
#define DATA_NODE_CPU_TEMP_DLC                                            (8)

#define DATA_NODE_LAST_BOOT_TIMESTAMP_ID                                  (0x51B) /**< node last boot timestamp */
#define DATA_NODE_LAST_BOOT_TIMESTAMP_DLC                                 (8)

#define DATA_EXTERNAL_CURRENT3_ID                                         (0x51C) /**< external current3 */
#define DATA_EXTERNAL_CURRENT3_DLC                                        (8)

#define DATA_ANALOG_KNOB3_ID                                              (0x51D) /**< analog knob3 */
#define DATA_ANALOG_KNOB3_DLC                                             (6)

#define DATA_ANALOG_KNOB4_ID                                              (0x51E) /**< analog knob4 */
#define DATA_ANALOG_KNOB4_DLC                                             (6)

#define DATA_EXTERNAL_CURRENT4_ID                                         (0x51F) /**< external current4 */
#define DATA_EXTERNAL_CURRENT4_DLC                                        (8)

#define DATA_DISPLAY_OFF_ID                                               (0x520) /**< display off */
#define DATA_DISPLAY_OFF_DLC                                              (5)

#define DATA_DISPLAY_ON_ID                                                (0x521) /**< display on */
#define DATA_DISPLAY_ON_DLC                                               (5)

#define DATA_DISPLAY_CLEAR_ID                                             (0x522) /**< display clear */
#define DATA_DISPLAY_CLEAR_DLC                                            (5)

#define DATA_DISPLAY_MODE_ID                                              (0x523) /**< display mode */
#define DATA_DISPLAY_MODE_DLC                                             (6)

#define DATA_ARGB_BUTTON_COLOR_ID                                         (0x524) /**< argb button color */
#define DATA_ARGB_BUTTON_COLOR_DLC                                        (7)

#define DATA_ARGB_BUTTON_LED_MODE_ID                                      (0x525) /**< argb button led mode */
#define DATA_ARGB_BUTTON_LED_MODE_DLC                                     (7)

#define DATA_EXTERNAL_TEMPERATURE2_ID                                     (0x526) /**< external temperature2 */
#define DATA_EXTERNAL_TEMPERATURE2_DLC                                    (8)

#define DATA_EXTERNAL_TEMPERATURE3_ID                                     (0x527) /**< external temperature3 */
#define DATA_EXTERNAL_TEMPERATURE3_DLC                                    (8)

#define DATA_EXTERNAL_TEMPERATURE4_ID                                     (0x528) /**< external temperature4 */
#define DATA_EXTERNAL_TEMPERATURE4_DLC                                    (8)

#define DATA_EXTERNAL_VOLTS2_ID                                           (0x529) /**< external volts2 */
#define DATA_EXTERNAL_VOLTS2_DLC                                          (8)

#define DATA_RESERVED_52A_ID                                              (0x52A) /**< 0x52A reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52A_DLC                                             (8)

#define DATA_RESERVED_52B_ID                                              (0x52B) /**< 0x52B reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52B_DLC                                             (8)

#define DATA_RESERVED_52C_ID                                              (0x52C) /**< 0x52C reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52C_DLC                                             (8)

#define DATA_RESERVED_52D_ID                                              (0x52D) /**< 0x52D reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52D_DLC                                             (8)

#define DATA_RESERVED_52E_ID                                              (0x52E) /**< 0x52E reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52E_DLC                                             (8)

#define DATA_RESERVED_52F_ID                                              (0x52F) /**< 0x52F reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_52F_DLC                                             (8)

#define DATA_RESERVED_530_ID                                              (0x530) /**< 0x530 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_530_DLC                                             (8)

#define DATA_RESERVED_531_ID                                              (0x531) /**< 0x531 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_531_DLC                                             (8)

#define DATA_RESERVED_532_ID                                              (0x532) /**< 0x532 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_532_DLC                                             (8)

#define DATA_RESERVED_533_ID                                              (0x533) /**< 0x533 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_533_DLC                                             (8)

#define DATA_RESERVED_534_ID                                              (0x534) /**< 0x534 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_534_DLC                                             (8)

#define DATA_RESERVED_535_ID                                              (0x535) /**< 0x535 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_535_DLC                                             (8)

#define DATA_RESERVED_536_ID                                              (0x536) /**< 0x536 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_536_DLC                                             (8)

#define DATA_RESERVED_537_ID                                              (0x537) /**< 0x537 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_537_DLC                                             (8)

#define DATA_RESERVED_538_ID                                              (0x538) /**< 0x538 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_538_DLC                                             (8)

#define DATA_RESERVED_539_ID                                              (0x539) /**< 0x539 reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_539_DLC                                             (8)

#define DATA_RESERVED_53A_ID                                              (0x53A) /**< 0x53A reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53A_DLC                                             (8)

#define DATA_RESERVED_53B_ID                                              (0x53B) /**< 0x53B reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53B_DLC                                             (8)

#define DATA_RESERVED_53C_ID                                              (0x53C) /**< 0x53C reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53C_DLC                                             (8)

#define DATA_RESERVED_53D_ID                                              (0x53D) /**< 0x53D reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53D_DLC                                             (8)

#define DATA_RESERVED_53E_ID                                              (0x53E) /**< 0x53E reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53E_DLC                                             (8)

#define DATA_RESERVED_53F_ID                                              (0x53F) /**< 0x53F reserved private msg for 64-bit sensor data */
#define DATA_RESERVED_53F_DLC                                             (8)

#define DISP_ANALOG_LED_STRIP_ID                                          (0x700) /**< analog led strip */
#define DISP_ANALOG_LED_STRIP_DLC                                         (7)

#define DISP_ARGBW_LED_STRIP_ID                                           (0x701) /**< argbw led strip */
#define DISP_ARGBW_LED_STRIP_DLC                                          (7)

#define DISP_ARGB_LED_STRIP_ID                                            (0x702) /**< argb led strip */
#define DISP_ARGB_LED_STRIP_DLC                                           (7)

#define DISP_RESERVED_703_ID                                              (0x703) /**< disp reserved 703 */
#define DISP_RESERVED_703_DLC                                             (7)

#define DISP_RESERVED_704_ID                                              (0x704) /**< disp reserved 704 */
#define DISP_RESERVED_704_DLC                                             (7)

#define DISP_OLED_ID                                                      (0x705) /**< non-touch oled display */
#define DISP_OLED_DLC                                                     (7)

#define DISP_RESERVED_706_ID                                              (0x706) /**< disp reserved 706 */
#define DISP_RESERVED_706_DLC                                             (7)

#define DISP_LCD_ID                                                       (0x707) /**< non-touch lcd display */
#define DISP_LCD_DLC                                                      (7)

#define DISP_RESERVED_708_ID                                              (0x708) /**< disp reserved 708 */
#define DISP_RESERVED_708_DLC                                             (4)

#define DISP_RESERVED_709_ID                                              (0x709) /**< disp reserved 709 */
#define DISP_RESERVED_709_DLC                                             (4)

#define DISP_RESERVED_70A_ID                                              (0x70A) /**< disp reserved 70a */
#define DISP_RESERVED_70A_DLC                                             (4)

#define DISP_RESERVED_70B_ID                                              (0x70B) /**< disp reserved 70b */
#define DISP_RESERVED_70B_DLC                                             (4)

#define DISP_RESERVED_70C_ID                                              (0x70C) /**< disp reserved 70c */
#define DISP_RESERVED_70C_DLC                                             (4)

#define DISP_RESERVED_70D_ID                                              (0x70D) /**< disp reserved 70d */
#define DISP_RESERVED_70D_DLC                                             (4)

#define DISP_RESERVED_70E_ID                                              (0x70E) /**< disp reserved 70e */
#define DISP_RESERVED_70E_DLC                                             (4)

#define DISP_RESERVED_70F_ID                                              (0x70F) /**< disp reserved 70f */
#define DISP_RESERVED_70F_DLC                                             (4)

#define INPUT_NO_BACKLIGHT_ID                                             (0x710) /**< input no backlight */
#define INPUT_NO_BACKLIGHT_DLC                                            (7)

#define INPUT_ARGB_BACKLIGHT_ID                                           (0x711) /**< input argb backlight */
#define INPUT_ARGB_BACKLIGHT_DLC                                          (7)

#define INPUT_ANALOG_BACKLIGHT_ID                                         (0x712) /**< input analog backlight */
#define INPUT_ANALOG_BACKLIGHT_DLC                                        (7)

#define INPUT_VIRTUAL_ID                                                  (0x713) /**< input virtual */
#define INPUT_VIRTUAL_DLC                                                 (7)

#define INPUT_WITH_DISPLAY_ID                                             (0x714) /**< input with display */
#define INPUT_WITH_DISPLAY_DLC                                            (7)

#define INPUT_ANALOG_KNOB_ID                                              (0x715) /**< analog knob input */
#define INPUT_ANALOG_KNOB_DLC                                             (7)

#define INPUT_JOG_DIAL_CLICK_ID                                           (0x716) /**< jog dial with click */
#define INPUT_JOG_DIAL_CLICK_DLC                                          (7)

#define INPUT_KEY_SWITCH_ID                                               (0x717) /**< key switch */
#define INPUT_KEY_SWITCH_DLC                                              (7)

#define INPUT_MOTION_DET_ID                                               (0x718) /**< motion detector */
#define INPUT_MOTION_DET_DLC                                              (7)

#define INPUT_CAP_TOUCH_ID                                                (0x719) /**< capacitive touch switch stand-alone */
#define INPUT_CAP_TOUCH_DLC                                               (7)

#define INPUT_JOG_DIAL_NOCLICK_ID                                         (0x71A) /**< jog dial without click */
#define INPUT_JOG_DIAL_NOCLICK_DLC                                        (7)

#define INPUT_RFID_READER_ID                                              (0x71B) /**< RFID reader input */
#define INPUT_RFID_READER_DLC                                             (7)

#define BUTTON_CONTACT_PULL_DOWN_ID                                       (0x71C) /**< button contact pull down */
#define BUTTON_CONTACT_PULL_DOWN_DLC                                      (7)

#define INPUT_CONTACT_PULL_UP_ID                                          (0x71D) /**< input contact pull up */
#define INPUT_CONTACT_PULL_UP_DLC                                         (7)

#define INPUT_RESERVED_71E_ID                                             (0x71E) /**< input reserved 71e */
#define INPUT_RESERVED_71E_DLC                                            (5)

#define INPUT_RESERVED_71F_ID                                             (0x71F) /**< input reserved 71f */
#define INPUT_RESERVED_71F_DLC                                            (5)

#define INPUT_DIGITAL_TEMP_ID                                             (0x720) /**< input digital temp */
#define INPUT_DIGITAL_TEMP_DLC                                            (5)

#define INPUT_K_TYPE_TEMP_ID                                              (0x721) /**< input k type temp */
#define INPUT_K_TYPE_TEMP_DLC                                             (5)

#define NODE_LASTBOOT_ID                                                  (0x722) /**< last boot timestamp */
#define NODE_LASTBOOT_DLC                                                 (5)

#define NODE_PCB_TEMP_ID                                                  (0x723) /**< node pcb temp */
#define NODE_PCB_TEMP_DLC                                                 (5)

#define NODE_CPU_TEMP_ID                                                  (0x724) /**< node cpu temp */
#define NODE_CPU_TEMP_DLC                                                 (5)

#define INPUT_EXT_VOLTAGE_SENSOR_ID                                       (0x725) /**< input ext voltage sensor */
#define INPUT_EXT_VOLTAGE_SENSOR_DLC                                      (5)

#define NODE_INT_VOLTAGE_SENSOR_ID                                        (0x726) /**< node int voltage sensor */
#define NODE_INT_VOLTAGE_SENSOR_DLC                                       (5)

#define NODE_INT_CURRENT_SENSOR_ID                                        (0x727) /**< node int current sensor */
#define NODE_INT_CURRENT_SENSOR_DLC                                       (5)

#define INPUT_EXT_CURRENT_SHUNT_ID                                        (0x728) /**< input ext current shunt */
#define INPUT_EXT_CURRENT_SHUNT_DLC                                       (5)

#define INPUT_EXT_CURRENT_HALL_ID                                         (0x729) /**< input ext current hall */
#define INPUT_EXT_CURRENT_HALL_DLC                                        (5)

#define SENSOR_RESERVED_72A_ID                                            (0x72A) /**< sensor reserved 72a */
#define SENSOR_RESERVED_72A_DLC                                           (5)

#define SENSOR_RESERVED_72B_ID                                            (0x72B) /**< sensor reserved 72b */
#define SENSOR_RESERVED_72B_DLC                                           (5)

#define SENSOR_RESERVED_72C_ID                                            (0x72C) /**< sensor reserved 72c */
#define SENSOR_RESERVED_72C_DLC                                           (5)

#define SENSOR_RESERVED_72D_ID                                            (0x72D) /**< sensor reserved 72d */
#define SENSOR_RESERVED_72D_DLC                                           (5)

#define SENSOR_RESERVED_72E_ID                                            (0x72E) /**< sensor reserved 72e */
#define SENSOR_RESERVED_72E_DLC                                           (5)

#define SENSOR_RESERVED_72F_ID                                            (0x72F) /**< sensor reserved 72f */
#define SENSOR_RESERVED_72F_DLC                                           (5)

#define INPUT_AMBIENT_LIGHT_ID                                            (0x730) /**< input ambient light */
#define INPUT_AMBIENT_LIGHT_DLC                                           (5)

#define IMU_X_AXIS_SENSOR_ID                                              (0x731) /**< IMU X Axis sensor */
#define IMU_X_AXIS_SENSOR_DLC                                             (5)

#define IMU_Y_AXIS_SENSOR_ID                                              (0x732) /**< IMU Y Axis sensor */
#define IMU_Y_AXIS_SENSOR_DLC                                             (5)

#define IMU_Z_AXIS_SENSOR_ID                                              (0x733) /**< IMU Z Axis sensor */
#define IMU_Z_AXIS_SENSOR_DLC                                             (5)

#define IMU_X_GYRO_SENSOR_ID                                              (0x734) /**< IMU X Gyro sensor */
#define IMU_X_GYRO_SENSOR_DLC                                             (5)

#define IMU_Y_GYRO_SENSOR_ID                                              (0x735) /**< IMU Y Gyro sensor */
#define IMU_Y_GYRO_SENSOR_DLC                                             (5)

#define IMU_Z_GYRO_SENSOR_ID                                              (0x736) /**< IMU Z Gyro sensor */
#define IMU_Z_GYRO_SENSOR_DLC                                             (5)

#define IMU_TEMP_SENSOR_ID                                                (0x737) /**< IMU temp sensor */
#define IMU_TEMP_SENSOR_DLC                                               (5)

#define GPS_UTC_TIME_ID                                                   (0x738) /**< GPS utc time */
#define GPS_UTC_TIME_DLC                                                  (5)

#define GPS_LATITUDE_ID                                                   (0x739) /**< GPS latitude */
#define GPS_LATITUDE_DLC                                                  (5)

#define GPS_NS_IND_ID                                                     (0x73A) /**< GPS NS IND */
#define GPS_NS_IND_DLC                                                    (5)

#define GPS_LONGITUDE_ID                                                  (0x73B) /**< GPS longitude */
#define GPS_LONGITUDE_DLC                                                 (5)

#define GPS_EW_IND_ID                                                     (0x73C) /**< GPS EW IND */
#define GPS_EW_IND_DLC                                                    (5)

#define GPS_ALTITUDE_ID                                                   (0x73D) /**< GPS altitude */
#define GPS_ALTITUDE_DLC                                                  (5)

#define GPS_STATUS_ID                                                     (0x73E) /**< GPS status */
#define GPS_STATUS_DLC                                                    (5)

#define SENSOR2_RESERVED_73F_ID                                           (0x73F) /**< sensor2 reserved 73f */
#define SENSOR2_RESERVED_73F_DLC                                          (4)

#define OUT_HIGH_CURRENT_SW_ID                                            (0x740) /**< high current solid state switch */
#define OUT_HIGH_CURRENT_SW_DLC                                           (7)

#define OUT_LOW_CURRENT_SW_ID                                             (0x741) /**< low current solid state switch */
#define OUT_LOW_CURRENT_SW_DLC                                            (7)

#define OUT_OPEN_DRAIN_ID                                                 (0x742) /**< open drain output */
#define OUT_OPEN_DRAIN_DLC                                                (7)

#define OUT_MECH_RELAY_ID                                                 (0x743) /**< mechanical relay */
#define OUT_MECH_RELAY_DLC                                                (7)

#define OUT_RESERVED_744_ID                                               (0x744) /**< out reserved 744 */
#define OUT_RESERVED_744_DLC                                              (4)

#define OUT_RESERVED_745_ID                                               (0x745) /**< out reserved 745 */
#define OUT_RESERVED_745_DLC                                              (4)

#define OUT_RESERVED_746_ID                                               (0x746) /**< out reserved 746 */
#define OUT_RESERVED_746_DLC                                              (4)

#define OUT_RESERVED_747_ID                                               (0x747) /**< out reserved 747 */
#define OUT_RESERVED_747_DLC                                              (4)

#define OUT_RESERVED_748_ID                                               (0x748) /**< out reserved 748 */
#define OUT_RESERVED_748_DLC                                              (4)

#define OUT_RESERVED_749_ID                                               (0x749) /**< out reserved 749 */
#define OUT_RESERVED_749_DLC                                              (4)

#define OUT_RESERVED_74A_ID                                               (0x74A) /**< out reserved 74a */
#define OUT_RESERVED_74A_DLC                                              (4)

#define OUT_RESERVED_74B_ID                                               (0x74B) /**< out reserved 74b */
#define OUT_RESERVED_74B_DLC                                              (4)

#define OUT_RESERVED_74C_ID                                               (0x74C) /**< out reserved 74c */
#define OUT_RESERVED_74C_DLC                                              (4)

#define OUT_RESERVED_74D_ID                                               (0x74D) /**< out reserved 74d */
#define OUT_RESERVED_74D_DLC                                              (4)

#define OUT_RESERVED_74E_ID                                               (0x74E) /**< out reserved 74e */
#define OUT_RESERVED_74E_DLC                                              (4)

#define OUT_RESERVED_74F_ID                                               (0x74F) /**< out reserved 74f */
#define OUT_RESERVED_74F_DLC                                              (4)

#define INTRO_RESERVED_750_ID                                             (0x750) /**< intro reserved 750 */
#define INTRO_RESERVED_750_DLC                                            (4)

#define INTRO_RESERVED_751_ID                                             (0x751) /**< intro reserved 751 */
#define INTRO_RESERVED_751_DLC                                            (4)

#define INTRO_RESERVED_752_ID                                             (0x752) /**< intro reserved 752 */
#define INTRO_RESERVED_752_DLC                                            (4)

#define INTRO_RESERVED_753_ID                                             (0x753) /**< intro reserved 753 */
#define INTRO_RESERVED_753_DLC                                            (4)

#define INTRO_RESERVED_754_ID                                             (0x754) /**< intro reserved 754 */
#define INTRO_RESERVED_754_DLC                                            (4)

#define INTRO_RESERVED_755_ID                                             (0x755) /**< intro reserved 755 */
#define INTRO_RESERVED_755_DLC                                            (4)

#define INTRO_RESERVED_756_ID                                             (0x756) /**< intro reserved 756 */
#define INTRO_RESERVED_756_DLC                                            (4)

#define INTRO_RESERVED_757_ID                                             (0x757) /**< intro reserved 757 */
#define INTRO_RESERVED_757_DLC                                            (4)

#define INTRO_RESERVED_758_ID                                             (0x758) /**< intro reserved 758 */
#define INTRO_RESERVED_758_DLC                                            (4)

#define INTRO_RESERVED_759_ID                                             (0x759) /**< intro reserved 759 */
#define INTRO_RESERVED_759_DLC                                            (4)

#define INTRO_RESERVED_75A_ID                                             (0x75A) /**< intro reserved 75a */
#define INTRO_RESERVED_75A_DLC                                            (4)

#define INTRO_RESERVED_75B_ID                                             (0x75B) /**< intro reserved 75b */
#define INTRO_RESERVED_75B_DLC                                            (4)

#define INTRO_RESERVED_75C_ID                                             (0x75C) /**< intro reserved 75c */
#define INTRO_RESERVED_75C_DLC                                            (4)

#define INTRO_RESERVED_75D_ID                                             (0x75D) /**< intro reserved 75d */
#define INTRO_RESERVED_75D_DLC                                            (4)

#define INTRO_RESERVED_75E_ID                                             (0x75E) /**< intro reserved 75e */
#define INTRO_RESERVED_75E_DLC                                            (4)

#define INTRO_RESERVED_75F_ID                                             (0x75F) /**< intro reserved 75f */
#define INTRO_RESERVED_75F_DLC                                            (4)

#define SYS_RESERVED_760_ID                                               (0x760) /**< sys reserved 760 */
#define SYS_RESERVED_760_DLC                                              (4)

#define SYS_RESERVED_761_ID                                               (0x761) /**< sys reserved 761 */
#define SYS_RESERVED_761_DLC                                              (4)

#define SYS_RESERVED_762_ID                                               (0x762) /**< sys reserved 762 */
#define SYS_RESERVED_762_DLC                                              (4)

#define SYS_RESERVED_763_ID                                               (0x763) /**< sys reserved 763 */
#define SYS_RESERVED_763_DLC                                              (4)

#define SYS_RESERVED_764_ID                                               (0x764) /**< sys reserved 764 */
#define SYS_RESERVED_764_DLC                                              (4)

#define SYS_RESERVED_765_ID                                               (0x765) /**< sys reserved 765 */
#define SYS_RESERVED_765_DLC                                              (4)

#define SYS_RESERVED_766_ID                                               (0x766) /**< sys reserved 766 */
#define SYS_RESERVED_766_DLC                                              (4)

#define SYS_RESERVED_767_ID                                               (0x767) /**< sys reserved 767 */
#define SYS_RESERVED_767_DLC                                              (4)

#define SYS_RESERVED_768_ID                                               (0x768) /**< sys reserved 768 */
#define SYS_RESERVED_768_DLC                                              (4)

#define SYS_RESERVED_769_ID                                               (0x769) /**< sys reserved 769 */
#define SYS_RESERVED_769_DLC                                              (4)

#define SYS_RESERVED_76A_ID                                               (0x76A) /**< sys reserved 76a */
#define SYS_RESERVED_76A_DLC                                              (4)

#define SYS_RESERVED_76B_ID                                               (0x76B) /**< sys reserved 76b */
#define SYS_RESERVED_76B_DLC                                              (4)

#define SYS_RESERVED_76C_ID                                               (0x76C) /**< sys reserved 76c */
#define SYS_RESERVED_76C_DLC                                              (4)

#define SYS_RESERVED_76D_ID                                               (0x76D) /**< sys reserved 76d */
#define SYS_RESERVED_76D_DLC                                              (4)

#define SYS_RESERVED_76E_ID                                               (0x76E) /**< sys reserved 76e */
#define SYS_RESERVED_76E_DLC                                              (4)

#define SYS_RESERVED_76F_ID                                               (0x76F) /**< sys reserved 76f */
#define SYS_RESERVED_76F_DLC                                              (4)

#define SYS_RESERVED_770_ID                                               (0x770) /**< sys reserved 770 */
#define SYS_RESERVED_770_DLC                                              (4)

#define SYS_RESERVED_771_ID                                               (0x771) /**< sys reserved 771 */
#define SYS_RESERVED_771_DLC                                              (4)

#define SYS_RESERVED_772_ID                                               (0x772) /**< sys reserved 772 */
#define SYS_RESERVED_772_DLC                                              (4)

#define SYS_RESERVED_773_ID                                               (0x773) /**< sys reserved 773 */
#define SYS_RESERVED_773_DLC                                              (4)

#define SYS_RESERVED_774_ID                                               (0x774) /**< sys reserved 774 */
#define SYS_RESERVED_774_DLC                                              (4)

#define SYS_RESERVED_775_ID                                               (0x775) /**< sys reserved 775 */
#define SYS_RESERVED_775_DLC                                              (4)

#define SYS_RESERVED_776_ID                                               (0x776) /**< sys reserved 776 */
#define SYS_RESERVED_776_DLC                                              (4)

#define SYS_RESERVED_777_ID                                               (0x777) /**< sys reserved 777 */
#define SYS_RESERVED_777_DLC                                              (4)

#define SYS_RESERVED_778_ID                                               (0x778) /**< sys reserved 778 */
#define SYS_RESERVED_778_DLC                                              (4)

#define SYS_RESERVED_779_ID                                               (0x779) /**< sys reserved 779 */
#define SYS_RESERVED_779_DLC                                              (4)

#define SYS_RESERVED_77A_ID                                               (0x77A) /**< sys reserved 77a */
#define SYS_RESERVED_77A_DLC                                              (4)

#define SYS_RESERVED_77B_ID                                               (0x77B) /**< sys reserved 77b */
#define SYS_RESERVED_77B_DLC                                              (4)

#define SYS_RESERVED_77C_ID                                               (0x77C) /**< sys reserved 77c */
#define SYS_RESERVED_77C_DLC                                              (4)

#define SYS_RESERVED_77D_ID                                               (0x77D) /**< sys reserved 77d */
#define SYS_RESERVED_77D_DLC                                              (4)

#define SYS_RESERVED_77E_ID                                               (0x77E) /**< sys reserved 77e */
#define SYS_RESERVED_77E_DLC                                              (4)

#define SYS_RESERVED_77F_ID                                               (0x77F) /**< sys reserved 77f */
#define SYS_RESERVED_77F_DLC                                              (4)

#define BOX_SW_3GANG_ID                                                   (0x780) /**< 3 gang switch box, 2 high, 1 low */
#define BOX_SW_3GANG_DLC                                                  (6)

#define BOX_SW_4GANG_ID                                                   (0x781) /**< 4-gang switch box, 2 high, 2 low */
#define BOX_SW_4GANG_DLC                                                  (6)

#define BOX_SW_6GANG_HIGH_ID                                              (0x782) /**< 6-gang switch box, 4 high, 2 low */
#define BOX_SW_6GANG_HIGH_DLC                                             (6)

#define BOX_SW_6GANG_LOW_ID                                               (0x783) /**< 6-gang switch box, 2 high, 4 low */
#define BOX_SW_6GANG_LOW_DLC                                              (6)

#define BOX_SW_2GANG_HIGH_ID                                              (0x784) /**< 2-gang switch box, 2 high */
#define BOX_SW_2GANG_HIGH_DLC                                             (6)

#define BOX_SW_2GANG_LOW_ID                                               (0x785) /**< 2-gang switch box, 2 low */
#define BOX_SW_2GANG_LOW_DLC                                              (6)

#define BOX_MULTI_4XTEMP_ID                                               (0x786) /**< 4-digital multi temp input box */
#define BOX_MULTI_4XTEMP_DLC                                              (6)

#define BOX_SW_4RELAY_ID                                                  (0x787) /**< 4-gang relay output box */
#define BOX_SW_4RELAY_DLC                                                 (6)

#define BOX_MULTI_TVA_ID                                                  (0x788) /**< temp, volt, current input box */
#define BOX_MULTI_TVA_DLC                                                 (6)

#define BOX_SW_8RELAY_ID                                                  (0x789) /**< 8-gang relay output box */
#define BOX_SW_8RELAY_DLC                                                 (6)

#define BOX_MULTI_4X4IO_ID                                                (0x78A) /**< input - output box, 4 in, 4 out */
#define BOX_MULTI_4X4IO_DLC                                               (6)

#define BOX_MULTI_IO_ID                                                   (0x78B) /**< input - output box, multiple options */
#define BOX_MULTI_IO_DLC                                                  (6)

#define BOX_RESERVED_78C_ID                                               (0x78C) /**< box reserved 78c */
#define BOX_RESERVED_78C_DLC                                              (4)

#define BOX_RESERVED_78D_ID                                               (0x78D) /**< box reserved 78d */
#define BOX_RESERVED_78D_DLC                                              (4)

#define BOX_RESERVED_78E_ID                                               (0x78E) /**< box reserved 78e */
#define BOX_RESERVED_78E_DLC                                              (4)

#define BOX_RESERVED_78F_ID                                               (0x78F) /**< box reserved 78f */
#define BOX_RESERVED_78F_DLC                                              (4)

#define IFACE_8X4_ARGB_KEYPAD_ID                                          (0x790) /**< 8x4 argb keypad */
#define IFACE_8X4_ARGB_KEYPAD_DLC                                         (6)

#define IFACE_4X4_ARGB_KEYPAD_ID                                          (0x791) /**< 4x4 argb keypad */
#define IFACE_4X4_ARGB_KEYPAD_DLC                                         (6)

#define IFACE_TOUCHSCREEN_TYPE_A_ID                                       (0x792) /**< touchscreen type a */
#define IFACE_TOUCHSCREEN_TYPE_A_DLC                                      (6)

#define IFACE_TOUCHSCREEN_TYPE_B_ID                                       (0x793) /**< touchscreen type b */
#define IFACE_TOUCHSCREEN_TYPE_B_DLC                                      (6)

#define IFACE_NEXTION_TYPE_A_ID                                           (0x794) /**< nextion type a */
#define IFACE_NEXTION_TYPE_A_DLC                                          (6)

#define IFACE_NEXTION_TYPE_B_ID                                           (0x795) /**< nextion type b */
#define IFACE_NEXTION_TYPE_B_DLC                                          (6)

#define IFACE_RESERVED_796_ID                                             (0x796) /**< iface reserved 796 */
#define IFACE_RESERVED_796_DLC                                            (6)

#define IFACE_RESERVED_797_ID                                             (0x797) /**< iface reserved 797 */
#define IFACE_RESERVED_797_DLC                                            (6)

#define IFACE_RESERVED_798_ID                                             (0x798) /**< iface reserved 798 */
#define IFACE_RESERVED_798_DLC                                            (4)

#define IFACE_6_AXIS_IMU_ID                                               (0x799) /**< 6 axis imu */
#define IFACE_6_AXIS_IMU_DLC                                              (6)

#define IFACE_3X5_BUTTON_BOX_ID                                           (0x79A) /**< 3x5 button box */
#define IFACE_3X5_BUTTON_BOX_DLC                                          (6)

#define IFACE_4X6_BUTTON_BOX_ID                                           (0x79B) /**< 4x6 button box */
#define IFACE_4X6_BUTTON_BOX_DLC                                          (6)

#define IFACE_RESERVED_79C_ID                                             (0x79C) /**< iface reserved 79c */
#define IFACE_RESERVED_79C_DLC                                            (4)

#define IFACE_RESERVED_79D_ID                                             (0x79D) /**< iface reserved 79d */
#define IFACE_RESERVED_79D_DLC                                            (4)

#define IFACE_RESERVED_79E_ID                                             (0x79E) /**< iface reserved 79e */
#define IFACE_RESERVED_79E_DLC                                            (4)

#define IFACE_RESERVED_79F_ID                                             (0x79F) /**< iface reserved 79f */
#define IFACE_RESERVED_79F_DLC                                            (4)

#endif /* CANBUS_MSG_H_ */